sudo: required
language: cpp
dist: trusty
# install:
#   - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
# addons:
#   apt:
#     sources:
#       - boost-latest
#       - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
#       - ubuntu-toolchain-r-test
#     packages:
#       - cmake
#       - cmake-data
#       - libboost-dev
#       - gcc-4.8
#       - g++-4.8
os:
  - linux
  - osx
compiler:
  # - clang
  - gcc
script:
  - cmake -DCMAKE_BUILD_TYPE=Release && make -j4
